### ISSUE TITLE
Cannot enable automatic language switching in Multispeech when used with Emacspeak

### ISSUE THREAD

**Issue by sevapopov2** [poretsky/multispeech#1]
Hello,
I could compile Ru_tts, Rulex and multispeech on Arch and use Multispeech as a server for Emacspeak.
However, I cannot configure the automatic language switching for ru_tts and Mbrola.
I edit the configuration file that is provided in /usr/local/etc/multispeech.conf.
Here is what I did:
I set Mbrola for English language as engine since I cannot find freephone, uncommented lines to use ru_tts engine for Russian, charset line that specifies koi8r charset, the line to autodetect languages and tried to set priorities for Russian language as 2 for Russian and 1 for English.
But the issue is that the voice doesn't switch from English to Russian in Emacspeak when reading the manual for Emacs, Russian letters are read with Mbrola.
When switching to Ru_tts in speech-dispatcher the Russian voice works.
What could I try to do to make the automatic language switching to work?
Thank you!

**Comment by poretsky** [comment]
At first, I'd recommend experimenting in ~/.multispeechrc rather than in
the system wide configuration, leaving the latter untouched. Technically
it would be easier and all the tweaks would be compact and clearly
visible. In that case you could simply cite this file. Note that an
exact citation is always much better than a description.

What the charset line you mean? There are two such line in the
configuration file: one for input charset and another for the user TTS
charset. And both should be leaved untouched in most situations. Please,
read carefully the accompanying comments.

Why do you decided to set explicit priorities? Languages are scanned in
the ascending priority order. Thus, in you case English will be used
each time when it is detected. Multispeech doesn't split messages. So,
if English and Russian are present both, then English is used as
prioritised one.

In addition, a fallback language can be set in the speech section. And
I'd recomment to set engine as disabled for all unused languages.

**Comment by sevapopov2** [comment]
Hello Igor,
Thank you for answering my questions. I will answer yours below and attach the content of my .multispeechrc file.

> At first, I'd recommend experimenting in ~/.multispeechrc rather than in the system wide configuration, leaving the latter untouched. Technically it would be easier and all the tweaks would be compact and clearly visible. In that case you could simply cite this file. Note that an exact citation is always much better than a description. What the charset line you mean? There are two such line in the configuration file: one for input charset and another for the user TTS charset. And both should be leaved untouched in most situations. 

I uncommented the input charset line in the hope that it will fix the situation with language switching. But it didn't help and I replaced the file with the sample one back.

> Why do you decided to set explicit priorities? Languages are scanned in the ascending priority order. Thus, in you case English will be used each time when it is detected. Multispeech doesn't split messages. So, if English and Russian are present both, then English is used as prioritised one. In addition, a fallback language can be set in the speech section. And I'd recomment to set engine as disabled for all unused languages.

I set the priorities in hope that it will work but unfortunately it didn't, so as I told I replaced the file for general config with the sample one back to leave anything untouched.
I tried to disable all not needed languages in .multispeechrc file but unfortunately Russian voice still doesn't work. However, it works in Orca as I mentioned.
Here is the contents of .multispeechrc file:

```
# Setting up speech settings for multispeech.
[speech]
language = autodetect
fallback = ru
[en]
engine = mbrola
[ru]
engine = ru_tts
[de]
engine = disabled
[fr]
engine = disabled
[es]
engine = disabled
[it]
engine = disabled
[pt]
engine = disabled

[mbrola]
voices = /usr/share/mbrola
```

Thank you!

**Comment by poretsky** [comment]
Definitely it should work. But it doesn't. And, moreover, it works for
Orca as you report. So, I suppose that it is a fault of Emacs or
Emacspeak. Hope, it can be fixed by customizing Emacs.

Anyway, your Multispeech settings look absolutely correct and
sufficient.

**Comment by sevapopov2** [comment]
I tried to reinstall emacspeak but unfortunately it didn't work.
However, everything works as needed on my Debian 11's virtual machine with pre-compiled packages but doesn't work for Arch.
Should automatic language switching work for Orca by default too?
If yes, then it doesn't work in my case.
Unfortunately I cannot check that on Debian since I cannot set up the multispeech's speech_dispatcher module like I could do that in Arch, putting sd_multispeech in /usr/lib/speech-dispatcher-modules doesn't make the server available in Orca's settings in Debian so I cannot check.
Thank you!

**Comment by poretsky** [comment]
There are ready to use packages for Debian 11. See
https://poretsky.github.io/packages and install not only multispeech,
but sd-multispeech as well. No need to place files by hand. And I'd
recommend the other packages from that suite too, especially emacspeak.

**Comment by sevapopov2** [comment]
Hello Igor,
Again, thank you for answering my questions.
Here are some things I have found. Shortly, the reason why language switching doesn't work is because of emacspeak. I tried to compile Emacspeak on Debian by myself and it also doesn't work as on Arch so the problem is there. I checked and on both systems language switching works when I run and check multispeech server independently by command:

```
multispeech
q hello
d
q привет
d
```

In that case the language switches according to the typed text.
Here are the steps that I use to configure emacspeak and multispeech by myself on Arch and Debian when compiling it from source:
I suppose there is an error.
1. I clone Emacspeak's repository:

```
git clone https://github.com/tvraman/emacspeak
```

2. I compile it by make command.
3. I put multispeech server that was compiled before from /usr/local/bin/multispeech to /home/user/emacspeak-path/servers/
4. I set the DTK_PROGRAM environment variable in my .zshrc to

```
export DTK_PROGRAM=multispeech
```

5. I launch Emacspeak by setting up the following line in /home/user/.emacs.d/init.el:

```
(load-file "/home/seva/Apps/emacspeak/lisp/emacspeak-setup.el")
```

Then launch emacs by typing emacs in the command line.
In that case language switching doesn't work, I suppose I do something wrong with multispeech setup...
I will appreciate any help,
Thank you!

**Comment by sevapopov2** [comment]
Sorry, I meant I copied executable from /usr/local/bin/multispeech to /home/user/emacspeak-path/servers.

**Comment by poretsky** [comment]
At a glance your actions look reasonable and correct. But I can say
almost nothing about Emacspeak from the upstream master branch. And I
think here is not a place for such discussion.

Anyway, what is your purpose? If you want to get functional multilingual
Emacspeak environment backed by Multispeech, I've pointed a
straightforward way in my previous comment.

**Comment by sevapopov2** [comment]
Ok, I might contact Emacspeak developers about this. As far as the reason I would like to make this work is because I'd like to set the environment up in Arch Linux which is my prefered Linux distribution. Also the reason why I'd like to set this up is because if I set Espeak as a speech server for Emacspeak, English voice is activated and I cannot read Russian Emacs tutorial provided there for beginners. Things work perfectly on Debian but I'd like to set them up on Arch Linux if possible. Thank you.
